### PR TITLE
Add New Projects ✨

### PR DESCRIPTION
**Pull request by yezz123**
- I just Add some new Projects that I maintain recently, also I add a project created by @Abdenasser called Dr_scaffold 🚀

- Also, @JefferyHus or @yjose, I add a 2 simples workflow based on Awesome lint to check the README Format, and also the Link Availability! You could check the PR https://github.com/yezz123/awesome-morocco/pull/3 (Still in development Mode).

### CODE REVIEW

**Review by JefferyHus — APPROVED** [review]
LGTM

**Comment by JefferyHus** [comment]
@yjose not sure about the new hyperlinks, but it looks a good addition for me to make things easy for other to navigate to what they wish to see easily.

**Comment by yezz123** [comment]
> @yjose not sure about the new hyperlinks, but it looks a good addition for me to make things easy for others to navigate to what they wish to see easily.

Yes, we can delete the hyperlinks checker, and let only the linter!
As I see, the linter works to make this README look good and in an alphabetical way, this is the only feature that https://github.com/yezz123/awesome-morocco/blob/CI/.github/workflows/ci.yml do.

**Comment by yjose** [comment]
@yezz123 @JefferyHus looks good for me. let me know when the PR is ready for merge. 
I need to mention that we are planning to convert the repo to a website with http://awesome-morocco.com/ but we are still not sure how to do it. I would like to hear your thoughts too?

**Comment by yezz123** [comment]
> @yezz123 @JefferyHus looks good for me. let me know when the PR is ready for merge. I need to mention that we are planning to convert the repo to a website with http://awesome-morocco.com/ but we are still not sure how to do it. I would like to hear your thoughts too?

I guess this one is ready, I will try to fix this PR https://github.com/yezz123/awesome-morocco/pull/3 , then i will inform you 🚀

**Pull request merged**
