### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by MohcineDev**
add youtube channel
i think "Network" is the appropriate name so anyone interested to it can look directly to this reference

### CODE REVIEW

**Comment by JefferyHus** [comment]
It would be great if you explain a bit why `Network` is the appropriate label.

**Comment by MohcineDev** [comment]
as i said if anyone interested to it can look directly to this reference 
and when you get asked in your live videos about some network advise or resources " like i think in two videos before " you can give them this link
and network is what these teachers are talking about

**Comment by JefferyHus** [comment]
The thing is. If we split things into categories of tech stacks or by tools, then we will end up with a messy markdown. It will be so hard to find things. So, as long as you are adding YouTube channels, it will be easy to have #83 YouTube as a parent category & then add a description in front of your channel links. This way people can go to that section & find channels related to Network or something else.

**Comment by MohcineDev** [comment]
Done, sorry for taking your time!

**Review by JefferyHus — APPROVED** [review]

**Comment by JefferyHus** [comment]
LGTM @yjose @aboullaite

**Pull request merged**
