### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by MohcineDev**
learn some network basics from Moroccan teachers

### CODE REVIEW

**Comment by yjose** [comment]
thank you @MohcineDev  for your contribution but I think we still didn't figure out if we need to add a new section for youtube channels. 
let's see with the team if we need to add a new section for youtube channels
@aboullaite @ezzarghili @soufianelf @JefferyHus

**Comment by aboullaite** [comment]
For Youtube channels, I believe it make sense to have them, if the content is Moroccan and preferably en Darija. 
Twitter accounts and facebook pages should not be part of this repo IMHO

**Comment by MohcineDev** [comment]
🤔 yes they are moroccans

**Comment by aboullaite** [comment]
I know :) Can you please remove twitter accounts and keep only youtube channels. Also, Can you change Network to Video platforms or something similar

**Pull request closed without merging**
